---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
 name: next-carcenter-erding
spec:
 scaleTargetRef:
   apiVersion: apps/v1
   kind: Deployment
   name: next-carcenter-erding
 minReplicas: 2
 maxReplicas: 10
 targetCPUUtilizationPercentage: 50
...