apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: staging
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: palermo003@gmail.com
    privateKeySecretRef:
      name: staging.devrico003-tls
    solvers:
      - http01:
          ingress:
            class: nginx
