apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-jenkins
  namespace: devops-tools
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: palermo003@gmail.com
    privateKeySecretRef:
      name: jenkins.devrico003-tls
    solvers:
      - http01:
          ingress:
            class: nginx
