apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-staging
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-staging
  template:
    metadata:
      labels:
        app: mongodb-staging
    spec:
      volumes:
        - name: mongodb-data
          persistentVolumeClaim:
            claimName: mongodb-pvc-staging
      containers:
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
