apiVersion: v1
kind: Service
metadata:
  name: mongodb-service-staging 
  namespace: staging  
spec:
  selector:
    app: mongodb-staging  
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  type: ClusterIP
