apiVersion: v1
kind: Service
metadata:
  annotations:
    meta.helm.sh/release-name: ingress-nginx
    meta.helm.sh/release-namespace: ingress-nginx
    metallb.universe.tf/ip-allocated-from-pool: default
  creationTimestamp: "2024-01-09T19:39:02Z"
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: ingress-nginx
    app.kubernetes.io/part-of: ingress-nginx
    app.kubernetes.io/version: 1.9.5
    helm.sh/chart: ingress-nginx-4.9.0
  name: ingress-nginx-controller
  namespace: ingress-nginx
  resourceVersion: "10926312"
  uid: 128d55a3-8ec4-4ae9-9dd0-079589e07c6c
spec:
  allocateLoadBalancerNodePorts: true
  clusterIP: 10.98.132.139 # This is the internal IP address of the ingress-nginx-controller
  clusterIPs:
  - 10.98.132.139 # This is the internal IP address of the ingress-nginx-controller
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - appProtocol: http
    name: http
    nodePort: 31546
    port: 80
    protocol: TCP
    targetPort: http
  - appProtocol: https
    name: https
    nodePort: 30832
    port: 443
    protocol: TCP
    targetPort: https
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: xxx.xxx.xxx.xxx # This is the external IP address of the ingress-nginx-controller
